version: "3.9"

services:

  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=medicalpatient
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    ports:
      - '3307:3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  mongodb_container:
    image: mongo:6.0.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test@1234
    ports:
      - 27017:27017
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js


  apipatient:
    build: ./apipatient
    restart: always
    ports:
      - "8082:8082"
   
  notes:
    build: ./notes
    restart: always
    ports:
      - "8083:8083"
    depends_on:
      - apipatient

  assessment:
    build: ./assessment
    restart: always
    ports:
      - "8084:8084"
    depends_on:
      - notes

  ui:
    build: ./ui
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - assessment

  gateway:
    build: ./gateway
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - ui
