version: "3.9"

services:
  apipatient:
    build: ./apipatient
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - gateway

  gateway:
    build: ./gateway
    restart: always
    ports:
      - "8081:8080"

  ui:
    build: ./ui
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - apipatient
