version: "3.9"

services:
  apipatient:
    build: ./apipatient
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - gateway

  notes:
    build: ./notes
    restart: always
    ports:
      - "8083:8083"
    depends_on:
      - gateway

  assessment:
    build: ./assessment
    restart: always
    ports:
      - "8084:8084"
    depends_on:
      - gateway

  gateway:
    build: ./gateway
    restart: always
    ports:
      - "8081:8081"

  ui:
    build: ./ui
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - apipatient
