version: "3.9"

services:

  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
      - MYSQL_DATABASE=medicalpatient
    ports:
      - '3307:3307'
    volumes:
      - mysql-data:/var/lib/mysql
      - /init.sql:/docker-entrypoint-initdb.d/init.sql  

  mongodb_container:
    image: mongo:6.0.2
    environment:
      - MONGO_DATABASE=medilab
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=test@1234
    ports:
      - 27017:27017

  apipatient:
    build: ./apipatient
    restart: always
    ports:
      - "8082:8082"
    environment:
      - MYSQL_HOST=mysql:3307
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
      - MYSQL_DATABASE=medicalpatient
    depends_on:
      - mysql

  notes:
    build: ./notes
    restart: always
    ports:
      - "8083:8083"
    environment:
      - MONGO_DATABASE=medilab
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=test@1234
    depends_on:
      - apipatient

  assessment:
    build: ./assessment
    restart: always
    ports:
      - "8084:8084"
    depends_on:
      - notes

  ui:
    build: ./ui
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - assessment

  gateway:
    build: ./gateway
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - ui

volumes:
  mysql-data:
  mongo-data:
